### ISSUE TITLE
GitHub Actions port?

### ISSUE THREAD

**Issue by nightlark** [mathworks/matlab-azure-devops-extension#41]
Hi, I tried to get the install steps running on GitHub Actions (see [this repository](https://github.com/nightlark/test-matlab-install/blob/main/.github/workflows/matlab-install.yml) for the results). Since GitHub is owned by Microsoft, I thought their runners should be running on a similar pool of VMs as the Azure Pipelines, possibly with an overlapping IP address block or something that would make matlab just work for CI using GitHub Actions for public repositories on GitHub.

Unfortunately, it looks like whatever it uses to check if its being installed on CI for a public repository doesn't pass, so it can't be installed/activated.

It would be great if you have plans for GitHub Actions support in the near future -- I find that the integration directly with GitHub makes it really convenient to work with compared to other CI choices, and their resource allocations for public projects are generous (at busy times, I've seen backlogs build up for Azure and Travis CI builds).

**Comment by mcafaro** [comment]
Hi @nightlark. We have GitHub Actions support available at https://github.com/matlab-actions . It is not listed in the GitHub Marketplace or MathWorks.com yet but is ready for you to try.

**Comment by nightlark** [comment]
Thanks @mcafaro, this is great! Looking forward to trying it out!😄
