### ISSUE TITLE
Support for Azure private projects

### ISSUE THREAD

**Issue by khaaliid** [mathworks/matlab-azure-devops-extension#85]
As mentioned in the plugin overview page this plugin is only available for the public projects. Will it be available for private projects as well ?

The following error is what I get when I am trying to run it from a private project.

`Unable to activate MATLAB. MATLAB activation is available only for public projects.`

**Comment by Volapyl** [comment]
How is this still not fixed ? 
Is there really no way to link an external license server such that the install can finish when running on an Azure hosted agent pool ? 

I have a pipeline running on my local machine using a self hosted agent setup running locally, but it is essentially the ultimate cloudversion of _it works on my machine_ which isn't really making for a robust setup :)

**Comment by acampbel** [comment]
Closing this issue as[ the documentation](https://marketplace.visualstudio.com/items?itemName=MathWorks.matlab-azure-devops-extension#use-matlab-batch-licensing-token) has been updated to point to leveraging batch tokens for licensing private projects
